### ISSUE TITLE
Slow Processing

### ISSUE THREAD

**Issue by JesseHerrick** [imathis/jekyll-minify-html#4]
Minification of my HTML is slowed by about 6 seconds when using this plugin. Is there any way to speed it up?

**Comment by rr-** [comment]
I have the same issue, only in my case it's a factor of additional 30 seconds.

Before enabling `jekyll-minify-html`:

    rr-@burza:/srv/www/sakuya-dev$ echo "minify_html: false" >> _config.yml
    rr-@burza:/srv/www/sakuya-dev$ time jekyll b
    Configuration file: /srv/www/sakuya-dev/_config.yml
                Source: /srv/www/sakuya-dev
           Destination: /srv/www/sakuya-dev/_site
          Generating...
                        done.
     Auto-regeneration: disabled. Use --watch to enable.
    
    real    0m3.910s
    user    0m3.640s
    sys     0m0.260s

After enabling `jekyll-minify-html`:

    rr-@burza:/srv/www/sakuya-dev$ echo "minify_html: true" >> _config.yml
    rr-@burza:/srv/www/sakuya-dev$ time jekyll b
    Configuration file: /srv/www/sakuya-dev/_config.yml
                Source: /srv/www/sakuya-dev
           Destination: /srv/www/sakuya-dev/_site
          Generating...
                        done.
     Auto-regeneration: disabled. Use --watch to enable.

    real    0m33.534s
    user    0m30.466s
    sys     0m3.036s

As for the number of posts - I have only about 100 of them:

    rr-@burza:/srv/www/sakuya-dev$ find _posts -type f|wc -l
    90

**Comment by imathis** [comment]
This plugin is mostly just an automated way of passing HTML through [html_press](https://github.com/stereobooster/html_press) so any speed optimizations would need to be made with in that project. There also may be a faster HTML compressor out there now. I used html_press because it seemed to work the best at the time.
